import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" href="./favicon.ico" type="image/x-icon" sizes="16x16" />
      </head> */}
      <body>
        {children}
      </body>
    </html>
  );
}
